arangodb/interactive_tutorials

- notebooks/ML_Collab_Article/Arangopipe_Generate_TF_Visualization.ipynb
- notebooks/ML_Collab_Article/Arangopipe_View_TF_Visualization.ipynb
- notebooks/ML_Collab_Article/ML_Collaboration_Dataset_Shift.ipynb
- notebooks/ML_Collab_Article/ML_Collaboration_Hyperopt_Integration.ipynb
- notebooks/ML_Collab_Article/ML_Collaboration_Model_Building.ipynb
- notebooks/ML_Collab_Article/README.md
- notebooks/ML_Collab_Article/example_output/Arangopipe_Generate_TF_Visualization_output.ipynb
- notebooks/ML_Collab_Article/example_output/Arangopipe_View_TF_Visualization_output.ipynb
- notebooks/ML_Collab_Article/example_output/ML_Collaboration_Dataset_Shift_output.ipynb
- notebooks/ML_Collab_Article/example_output/ML_Collaboration_Hyperopt_Integration_output.ipynb
- notebooks/ML_Collab_Article/example_output/ML_Collaboration_Model_Building_output.ipynb
Added links to the notebooks and readme for the now published article
> Added the now published article link

- notebooks/Pregel.ipynb
This is a WIP (included here for link check etc).
> Added first draft of Pregel Notebook.

- notebooks/Graph_Embeddings.ipynb
> I have added thorough description for each cell and code lines in the Graph Embedding notebook

- oasis.py
This PR:
* Adds connection verification checks when a `python-arango` connection is opened. This brings it in line with the `pyArango` connection that does this automatically.
* Increases the sleep time for `python-arango` and `pyArango` connection errors to give Oasis more time to process temporary user creation.
* Small formatting changes
> Increase Sleep Time, Add Python-Arango Verification & Fix Formatting

- notebooks/FuzzySearch.ipynb
> Updated notebook location.

- README.md
- notebooks/Collaborative_Filtering.ipynb
- notebooks/example_output/Collaborative_Filtering_output.ipynb
> Collaborative filtering

- tools/macos/arangoimport
- tools/macos/arangorestore
> adds macos tools

- README.md
- notebooks/Graph_Retail_DA_II.ipynb
- notebooks/example_output/Graph_Retail_DA_II.ipynb
NB4 complete draft with Chris's feedback addressed.
> Notebook 4 complete draft with Chris's feedback addressed.

- notebooks/AqlCrudTutorial.ipynb
- notebooks/example_output/AqlCrudTutorial_output.ipynb
> Fixed repo URL.

- notebooks/FuzzySearch.ipynb
- notebooks/example_output/FuzzySearch_output.ipynb
Updates the data import and restore to work off of new imdb branch.
> fixes data import and restore

- README.md
Hey guys, I just warming up with my first Arango community PR
> docs: Important:) readme fix

- notebooks/ArangoBnB_simple_data_exploration.ipynb
- notebooks/ArangoDB_NetworkX_Interface_Introduction.ipynb
- notebooks/Graph_Embeddings.ipynb
- notebooks/Graph_Retail_DA_I.ipynb
- notebooks/Graph_Retail_DA_II.ipynb
- notebooks/Graph_Retail_EDA_I.ipynb
- notebooks/Graph_Retail_EDA_II.ipynb
- notebooks/ML_Collab_Article/Arangopipe_Generate_TF_Visualization.ipynb
- notebooks/ML_Collab_Article/Arangopipe_View_TF_Visualization.ipynb
- notebooks/ML_Collab_Article/ML_Collaboration_Dataset_Shift.ipynb
- notebooks/ML_Collab_Article/ML_Collaboration_Hyperopt_Integration.ipynb
- notebooks/ML_Collab_Article/ML_Collaboration_Model_Building.ipynb
- notebooks/ML_Collab_Article/example_output/Arangopipe_Generate_TF_Visualization_output.ipynb
- notebooks/ML_Collab_Article/example_output/Arangopipe_View_TF_Visualization_output.ipynb
- notebooks/ML_Collab_Article/example_output/ML_Collaboration_Dataset_Shift_output.ipynb
- notebooks/ML_Collab_Article/example_output/ML_Collaboration_Hyperopt_Integration_output.ipynb
- notebooks/ML_Collab_Article/example_output/ML_Collaboration_Model_Building_output.ipynb
- notebooks/Matrix_Factorization_Freq_Shoppers.ipynb
- notebooks/example_output/ArangoBnB_simple_data_exploration_output.ipynb
- notebooks/example_output/Graph_Embeddings_output.ipynb
- notebooks/example_output/Graph_Retail_DA_II.ipynb
- notebooks/example_output/Graph_Retail_DA_I_output.ipynb
- notebooks/example_output/Graph_Retail_EDA_II_output.ipynb
- notebooks/example_output/Matrix_Factorization_Freq_Shoppers_output.ipynb
- notebooks/example_output/graph_retail_EDA_I_output.ipynb
Sets dependencies for arangopipe and adbnx_adapter to be their most known good versions. 
TODO: Update all notebooks to use newer versions.
> Arangopipe update

- oasis.py
> increase connector sleep time

- notebooks/ArangoDB_Graphistry_Visualization.ipynb
> Graphistry tutorial

- notebooks/ArangoDB_Graphistry_Visualization.ipynb
> Improved Graphistry notebook.

- notebooks/HybridSmartGraphs.ipynb
> Added link to benchmark definition.

- notebooks/arangoflix/similarMovie_MF_ML_Inference.ipynb
- notebooks/arangoflix/similarMovie_TFIDF_AQL_Inference.ipynb
- notebooks/arangoflix/similarMovie_TFIDF_ML_Inference.ipynb
- [x ] `tutorialName` for temporary DB (if applicable)
- [x ] Colab link added to ReadMe in the correct alphabetical order
- [x ] `nbstripout` ran on notebook
- [na ] Notebook with output added to the `example_output` folder with `_output` appended to filename
> small fixes

- README.md
> Changed ArangoGraph/Oasis name.

- README.md
- notebooks/ArangoDBLangChain.ipynb
- notebooks/Langchain.ipynb
- notebooks/example_output/Langchain_output.ipynb
This notebook is based on https://langchain-langchain.vercel.app/docs/use_cases/graph/graph_arangodb_qa.html
> new: LangChain notebook

- README.md
- notebooks/Langchain.ipynb
- notebooks/Langchain_Full.ipynb
- notebooks/example_output/Langchain_Full_output.ipynb
- notebooks/example_output/Langchain_output.ipynb
1. [LangChain.ipynb](https://colab.research.google.com/github/arangodb/interactive_tutorials/blob/langchain-notebook-variations/notebooks/Langchain.ipynb): The notebook from #104 
2. [LangChain_Full.ipynb](https://colab.research.google.com/github/arangodb/interactive_tutorials/blob/langchain-notebook-variations/notebooks/Langchain_Full.ipynb): The notebook from #105
> Proposing Langchain "simple" & "full" notebooks
